### ISSUE TITLE
PHP error in functions-dev.php

### ISSUE THREAD

**Issue by KevinFuret** [flurinduerst/WPSeed#32] opened 2019-08-07 14:58 UTC
Hey, 

Got this error when I load homepage just after installed the theme : 

```Parse error: syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in /Users/work/Documents/Dev/Sites/product-management/wp-content/themes/pm-theme/functions/functions-dev.php on line 229```

Thanks for the help!

**Comment by ghost** [comment] 2019-08-07 19:21
I'm also dealing with this issue. I don't see a syntax error in the file either. I removed it and the guttenberg functions file and commented out the functions from header.php as a quick fix.

 I was hosting this in Scotch Box locally and only encountered this issue on my remote staging server.

**Comment by flurinduerst** [comment] 2019-09-12 07:51
Hey. Can you tell me what file-version of `functions-dev` you were using? See `@version` in php-header at the top of the file.

**Comment by ghost** [comment] 2019-09-12 11:29
* @version     2.2.0

**Comment by akolinski** [comment] 2019-09-24 13:27
Having the same issue when using WPDistillery and running Vagrant up. The WPSeed theme has an error in the functions-dev.php on line 229. A fix needs to be merged in the master branch for the file.

**Comment by flurinduerst** [comment] 2019-11-25 15:13
do you have `short_open_tag` enabled on your webserver/VM?

**Comment by ghost** [comment] 2019-12-30 11:32
Same error here.  functions-dev.php version 2.2.0

**Comment by flurinduerst** [comment] 2020-01-07 08:07
@sirbene and @akolinski do you have `short_open_tag` enabled on your webserver/VM?

**Comment by akolinski** [comment] 2020-01-08 07:44
@flurinduerst just looked at my php.ini for the project yes `short_open_tag` is enabled.

**Comment by flurinduerst** [comment] 2020-01-08 12:26
I can't replicate the error. Also, there are no syntax errors. 

Could you remove function by function so you can tell which function is responsible for the error?

Also, what PHP-version are you using?

**Comment by akolinski** [comment] 2020-01-08 13:08
PHP version 7.0.18. The issue is in the functions-dev.php file on line 229.

**Comment by flurinduerst** [comment] 2020-01-08 15:00
line 229 is not where the error is.

Let's try that again: Could you remove function by function so you can tell which function is responsible for the error? Because I can't replicate the issue.

**Comment by akolinski** [comment] 2020-01-09 00:46
Not a problem. I'm going to set up a new WPDistillery instance and log the issues.

I have followed steps 1 to 4 here https://github.com/flurinduerst/WPDistillery#setup. At step 4 running `vagrant up` the provisioning of the box is being halted. I have attached the log which outlines functions and line numbers of the errors.

    default: [=== CONFIGURE THEME ===]
    default: »»» downloading WPSeed...
    default: Downloading installation package from https://github.com/flurinduerst/WPSeed/archive/master.zip...
    default: Unpacking the package...
    default: Installing the theme...
    default: Renamed Github-based project from 'WPSeed-master' to 'WPSeed'.
    default: PHP Warning:  fopen(/var/www/public/wp-content/upgrade/master-quS0y6/WPSeed/style.css): failed to open stream: No such file or directory in /var/www/public/wp-includes/functions.php on line 5782
    default: Warning: fopen(/var/www/public/wp-content/upgrade/master-quS0y6/WPSeed/style.css): failed to open stream: No such file or directory in /var/www/public/wp-includes/functions.php on line 5782
    default: PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5785
    default: Warning: fread() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5785
    default: PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5788
    default: Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/public/wp-includes/functions.php on line 5788
    default: Warning: The package could not be installed. "The <code>style.css</code> stylesheet doesn&#8217;t contain a valid theme header."
    default: Theme update failed.
    default: Warning: The 'https://github.com/flurinduerst/WPSeed/archive/master.zip' theme could not be found.
    default: Error: No themes installed.
    default:
    default: »»» aborting WPDistillery setup!
    default: bash: line 5: xit: command not found

In order to try to run again, you have to `vagrant destroy` and  `vagrant up` again.

**Comment by flurinduerst** [comment] 2020-01-09 10:12
Fixed in https://github.com/flurinduerst/WPSeed/commit/f7d2debab67ea9ccf499651623d7ebb07d6b2ff2

Found a Zero-width space in functions-dev.php which might have caused the problem (thanks to @scherii). 

@akolinski the error you posted in your newest post is not related to the the php-error this issue is about. The path to the theme seems wrong (`upgrade` instead of `themes`). I suggest you completely erase the current installation and try a new one with the updated WPSeed and a fresh WPDistillery installation. Feel free to create a new issue (probably over at https://github.com/flurinduerst/WPDistillery if the issue is related to the installation itself).

Would be great if anyone affected can confirm this fixed the issue.

**Comment by akolinski** [comment] 2020-01-09 10:22
Okay, I'll create a new issue in the WPDistillery repo. That's the thing, today I created a new installation of WPDistillery and got this issue. I'll try again and will see if I get the same issue.

**Comment by flurinduerst** [comment] 2020-01-09 10:42
Thanks. This issue, regarding the php-error in `functions-dev.php` should be fixed now :)

**Closed as completed** 2020-01-09 15:51 UTC
